#!/bin/bash
# Gerrit hook script that gets called after a comment gets added :-) with the
# following parameters:
# comment-added --change <change id> --change-url <change url> --project <project name>
#     --branch <branch> --author <comment author> --commit <commit> --comment <comment>
#     [--<approval category id> <score> --<approval category id> <score> ...]
#
# This script checks comment text to see if it is a comment that Jenkins made. It
# approves the platform specific verified categories.
# This is necessary since Jenkins puts all approvals into one category regardless of
# the settings if one event triggers multiple builds on the same server.
TEMP=$(getopt -o h --long change: --long change-url: --long project: --long branch: --long topic: --long author: --long commit: --long comment: --long CRVW: --long VRIF: --long VRLX: -n '$(basename $0)' -- "$@")

eval set -- "$TEMP"

if [ $# -lt 17 ]; then
	NOAPPROVALS=1
fi

while true ; do
	case "$1" in
		--change) CHANGE_ID=$2 ;;
		--change-url) CHANGE_URL=$2 ;;
		--project) PROJECT=$2 ;;
		--branch) BRANCH=$2 ;;
		--topic) TOPIC=$2 ;;
		--author) AUTHOR=$2 ;;
		--commit) COMMIT=$2 ;;
		--comment) MSG=$2 ;;
		--CRVW) ;;
		--VRIF) ;;
		--VRLX) ;;
		--) shift; break;;
		*) echo "Internal error! Unknown parameter $1" >> $GERRIT_SITE/logs/comment-added-hook ; exit 1 ;;
	esac
	shift 2
done

if [ $NOAPPROVAL ]; then
	# We don't have any approval categories - no relevant comment
	echo "No approval categories (Change $CHANGE_ID)"  >> $GERRIT_SITE/logs/comment-added-hook
	exit 0
fi

if ! echo -e "$MSG" | grep -q -E "/(Gerrit-)?[A-Z][A-Za-z_]+-(Linux|Win)(32|64|-all|-any)-([A-Za-z_0-9.]+-)?(debug|release)(-.+)?/" ; then
	# Comment doesn't mention any project - not relevant
	echo "Comment doesn't mention project (Change $CHANGE_ID)"  >> $GERRIT_SITE/logs/comment-added-hook
	exit 0
fi

IFS=$'\n'
TOADDCAT=
TOADDMSG=
for line in $MSG; do
	case $line in
		*-Linux32-*|*-Linux64-*|*-Linux-*)
			CATEGORY="--verified-\(linux\)"
			CATMSG="Verified-Linux"
			;;
		*-Win32*|-Win64*|*-Win-*)
			CATEGORY="--verified"
			CATMSG="Verified"
			;;
	esac
	RESULT=$(echo $line | awk '{print $3}')
	case $RESULT in
		SUCCESS)
			VAL="+1"
			;;
		FAILURE)
			VAL="-1"
			;;
		UNSTABLE)
			VAL="0"
			;;
		*)
			continue
			;;
	esac
	echo "Adding review: $CATEGORY $VAL for commit $COMMIT" >> $GERRIT_SITE/logs/comment-added-hook
	TOADDCAT="$TOADDCAT $CATEGORY $VAL"
	TOADDMSG="$TOADDMSG $CATMSG $VAL"
done

if [ -n "$TOADDCAT" ]; then
	ssh -l "Gerrit Code Review" -p 59418 localhost -i $GERRIT_SITE/etc/ssh_host_dsa_key \
		suexec --as jenkins -- \
		gerrit review $TOADDCAT --project $PROJECT \
		--message "\"Automatically added by comment-added hook: $TOADDMSG \"" $COMMIT
fi
