#!/bin/bash
# Run git gc --auto on all of Gerrit's git repos

#cd $HOME/review_site/git
#for repo in $(find -type d -name \*.git); do
#        cd $repo
#        git gc --quiet --auto > /dev/null
#        cd ..
#done

# Gerrit brings it's own garbage collector since 2.6, so use that
ssh localhost gerrit gc --all

